[package]
name = "SubgamePrune0923"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
csv = "1.3.1"
rayon = "1.11.0"
serde = {version = "1.0.226", features = ["derive"]}
serde_json = "1.0.145"
clap = { version = "4", features = ["derive"] }
rand = "0.9.2"
indicatif = "0.18.0"
